# Generated by Django 3.0.8 on 2021-02-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='Profile/dummy.png', null=True, upload_to='Profile/'),
        ),
    ]
