# Generated by Django 3.0.8 on 2021-02-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products_Details', '0007_destination_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='image',
        ),
        migrations.AddField(
            model_name='destination',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='product_image'),
        ),
        migrations.AddField(
            model_name='destination',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='product_image'),
        ),
        migrations.AddField(
            model_name='destination',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='product_image'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='feature_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_image'),
        ),
    ]
