# Generated by Django 3.0.8 on 2021-02-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products_Details', '0008_auto_20210211_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
