# Generated by Django 2.2.2 on 2021-02-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products_Details', '0010_auto_20210211_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='Products_Details.Add_category'),
        ),
    ]
