# Generated by Django 2.2.2 on 2021-02-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products_Details', '0013_auto_20210212_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
