# Generated by Django 3.1.6 on 2021-02-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=20)),
                ('rid', models.CharField(max_length=10)),
                ('tamt', models.IntegerField()),
            ],
        ),
    ]
