# Generated by Django 3.1.6 on 2021-02-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epay', '0002_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='pid',
            field=models.CharField(max_length=40),
        ),
    ]
