# Generated by Django 3.1.5 on 2021-02-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='text',
            field=models.TextField(default='Null'),
        ),
    ]
