# Generated by Django 3.1.5 on 2021-02-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='name',
            field=models.CharField(default='NULL', max_length=50),
        ),
    ]
